# Generated by Django 3.2 on 2021-06-25 19:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0002_answer'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Answer',
        ),
    ]
